include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: ignore
    one_member_abstracts: ignore
    lines_longer_than_80_chars: ignore
    constant_identifier_names: ignore
