name: app
description: Project template for Hancod Tech team
version: 2.0.0+2
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  excel: ^4.0.6
  # facebook_app_events: ^0.19.4
  # firebase_analytics: ^11.3.6
  # firebase_core: ^3.9.0
  # firebase_crashlytics: ^4.2.0
  # firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  flutter_web_plugins:
    sdk: flutter
  form_builder_extra_fields: ^12.1.0
  form_builder_validators: ^11.1.2
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  hancod_theme:
    git:
      url: https://github.com/Hancod-Digital/hancod_theme.git
      ref: duxbe-3.32.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: 
  json_annotation: ^4.9.0
  multi_dropdown: ^3.0.1
  objectbox: ^4.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  phone_form_field: ^10.0.2
  printing: ^5.14.2
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  scaled_app: ^2.3.0
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4
  timezone: ^0.10.0
  upgrader: ^11.3.1
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^7.0.0
  objectbox_generator: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/shared/utils/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
